### PR TITLE
Add scripted update workflow helper

### PR DESCRIPTION
**Pull request by dbast**
This is the process I often use to update feedstocks.

Just a collection of commands out of my git history combined with some glue code.

I thought it would make sense to share this by including it here.

Any thoughts on how to optimize this or how your process looks like are welcome.

Thanks

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks, @dbast! That's really helpful. Please note that conda-forge has a bot that does something similar. The bot is currently a little bit slow as the migration to GCC7 is still ongoing. But in an ideal world we do not need to do this manually.

Thanks a lot!

**Comment by dbast** [comment]
Thanks, yes, I know that the bot is doing the updates. I found it quite helpful to get a full diff between an existing recipe and a new skeleton run to even update parts of the recipe which the bot does not touch.

**Comment by jdblischak** [comment]
> I found it quite helpful to get a full diff between an existing recipe and a new skeleton run to even update parts of the recipe which the bot does not touch.

@dbast Thanks for sharing your solution! I agree it can be tedious to check the bot's update, especially for packages with lots of dependencies with minimum version requirements.

What operating system(s) have you tested this script on? Any reason to supsect it wouldn't work identically on Linux and macOS?

**Comment by dbast** [comment]
@jdblischak The script was fully developed and tested on macOS.

It is `shellcheck` clean and should run in any bash on Linux/macOS.

Maybe the `read -n1` is not optimal, because if you answer one of the questions with `y + enter` instead of `y` only, read will only take the `y` and the next question is answered with just `enter`.

**Pull request merged**
