### PR TITLE
Add license file for GPL2 or GPL3.

### PR DESCRIPTION
**Pull request by jdblischak**
If `license_family` is GPL3, the following will be added:

```
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'   # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'   # [win]
```

Similarly for GPL2:

```
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'   # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'   # [win]
```

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @jdblischak!

**Comment by jdblischak** [comment]
@bgruening Do you want 2 or 3 spaces between the `'` and the `#`?

This PR uses 3 spaces, modeled after your comment on one of my past PRs: https://github.com/conda-forge/staged-recipes/pull/3983#pullrequestreview-64918989

On the other hand, the conda-forge linter suggests using 2 spaces (it throws an error if there is only 1 space, however it allows 3 spaces).

> Selectors are suggested to take a `<two spaces>#<one space>[<expression>]` form.

**Comment by bgruening** [comment]
Two is probably the way forward. But as long as the linter does not complain :)

**Comment by jdblischak** [comment]
Easy enough to change to 2 spaces. Update coming shortly

**Comment by jdblischak** [comment]
Updated to 2 spaces:

```
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
```

```
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]
```

**Comment by jdblischak** [comment]
@bgruening Is there anything you would like me to update before this is merged?

**Comment by bgruening** [comment]
Just had dropped the ball here, sorry. Thanks for the reminder!

**Pull request merged**
