### PR TITLE
Support noarch recipes.

### PR DESCRIPTION
**Pull request by jdblischak**
cc: @isuruf @bgruening 

xref: https://github.com/regro/cf-scripts/pull/394#issuecomment-438405035

### CODE REVIEW

**Comment by isuruf** [comment]
license file path is the same now for unix and windows

**Comment by jdblischak** [comment]
> license file path is the same now for unix and windows

@isuruf When did that change happen? Was it implemented in https://github.com/conda-forge/r-base-feedstock/pull/61?

And just to confirm, by the same file path, you mean that Windows now also uses `/lib/R/share/licenses/`?

**Comment by isuruf** [comment]
Yes and yes

**Comment by jdblischak** [comment]
@isuruf Updated to always use the same file path

**Comment by bgruening** [comment]
Muha, you guys are amazing!

**Comment by bgruening** [comment]
@jdblischak we skipped 3.4.1 for now to avoid the problem with rebuilding. As 3.4.1. would also not be rebuild against GCC 7.

**Comment by isuruf** [comment]
FYI. you can do `# [win and r_base=='3.4.1']` to distinguish between 3.4.1 and 3.5.1

**Comment by jdblischak** [comment]
> we skipped 3.4.1 for now to avoid the problem with rebuilding. As 3.4.1. would also not be rebuild against GCC 7.

@bgruening Thanks for the explanation. I had missed PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/148

However, this still means that existing recipes with GPL licenses need to be updated for the license to be packaged for Windows. Is this something we should explore doing with the autotick bot? Or with separate PRs?

**Comment by jdblischak** [comment]
> FYI. you can do # [win and r_base=='3.4.1'] to distinguish between 3.4.1 and 3.5.1

@isuruf Good to know. Thanks!

**Comment by isuruf** [comment]
> However, this still means that existing recipes with GPL licenses need to be updated for the license to be packaged for Windows. Is this something we should explore doing with the autotick bot? Or with separate PRs?

PRs to the bot (to do this automatically) are welcome.

**Pull request merged**
